apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: app
data:
  API_BASE_URL: {{ .Values.config.apiBaseUrl | quote }}
  WORKOS_CLIENT_ID: {{ .Values.config.workosClientId | quote }}
  CONVEX_URL: {{ .Values.config.convexUrl | quote }}