apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/collectiongeek/collectiongeek-gitops.git
    targetRevision: main
    path: charts/backend
    helm:
      valueFiles:
        - values.yaml
        - values-test.yaml

  destination:
    # Replace with your test cluster API server URL
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m